version: '3.8'

services:
  tiktok-ruleta:
    build: 
      context: .
      dockerfile: Dockerfile.simple
      no_cache: true
    ports:
      - "3005:3005"
    volumes:
      - ruleta-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3005
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: tiktok-ruleta-app
    network_mode: "bridge"

volumes:
  ruleta-data:
    driver: local
