version: '3.8'

services:
  tiktok-ruleta:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ruleta-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3000
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: tiktok-ruleta-app
    network_mode: "bridge"

volumes:
  ruleta-data:
    driver: local
