version: '3.8'

services:
  tiktok-ruleta:
    build: .
    ports:
      - "3005:3005"
    volumes:
      - ruleta-data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3005
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    container_name: tiktok-ruleta-app

volumes:
  ruleta-data:
    driver: local
