version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: tiktok-live-osqui
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3005             # ← debe coincidir con lo que escucha tu app
      HOST: 0.0.0.0
      HOSTNAME: 0.0.0.0
      APP_HOSTNAME: ${APP_HOSTNAME}
    networks: [proxy]
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"

      # Router solo por 443 (TLS global ya está en el entrypoint)
      - "traefik.http.routers.tiktok.rule=Host(`${APP_HOSTNAME}`)"
      - "traefik.http.routers.tiktok.entrypoints=websecure"

      # 🔐 SSO en el borde (Authentik)
      - "traefik.http.routers.tiktok.middlewares=authentik@file,gzip@file,secure-headers@file"

      # Service → puerto interno real de tu app
      - "traefik.http.services.tiktok.loadbalancer.server.port=3005"

networks:
  proxy:
    external: true
